// <auto-generated />
using System;
using InvestmentHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027204849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentHub.Domain.Entities.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortfolioId");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Status");

                    b.HasIndex("PortfolioId", "Status");

                    b.ToTable("Investments", (string)null);
                });

            modelBuilder.Entity("InvestmentHub.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("InvestmentHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InvestmentHub.Domain.Entities.Investment", b =>
                {
                    b.HasOne("InvestmentHub.Domain.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InvestmentHub.Domain.ValueObjects.Money", "CurrentValue", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentValueAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CurrentValueCurrency");

                            b1.HasKey("InvestmentId");

                            b1.ToTable("Investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId");
                        });

                    b.OwnsOne("InvestmentHub.Domain.ValueObjects.Money", "PurchasePrice", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PurchasePriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PurchasePriceCurrency");

                            b1.HasKey("InvestmentId");

                            b1.ToTable("Investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId");
                        });

                    b.OwnsOne("InvestmentHub.Domain.ValueObjects.Symbol", "Symbol", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SymbolAssetType");

                            b1.Property<string>("Exchange")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SymbolExchange");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("SymbolTicker");

                            b1.HasKey("InvestmentId");

                            b1.ToTable("Investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId");
                        });

                    b.Navigation("CurrentValue")
                        .IsRequired();

                    b.Navigation("PurchasePrice")
                        .IsRequired();

                    b.Navigation("Symbol")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
